import { useEffect, useMemo, useRef, useState, type DragEvent } from 'react';
import './OrganizationPanel.css';

export type Folder = { id: string; name: string; order: number };
export type Project = { id: string; folderId: string | null; name: string; order: number };
export type Scope = { type: 'folder'; id: string } | { type: 'project'; id: string } | null;
export type OrganizationActions = {
  createFolder(name: string): void; renameFolder(id: string, name: string): void; deleteFolder(id: string): void;
  createProject(name: string, folderId: string | null): void; renameProject(id: string, name: string): void; deleteProject(id: string): void;
  moveProject(id: string, folderId: string | null, beforeId?: string): void; moveFolder(id: string, beforeId?: string): void;
  exportJson(): void; importJson(file: File): void; moveItemToProject?(itemId: string, projectId: string): void;
};
type Dialog = { type: 'folder' | 'project' | 'rename-folder' | 'rename-project' | 'delete-folder' | 'delete-project'; id?: string } | null;
const sort = <T extends { order: number; name: string }>(items: readonly T[]) => [...items].sort((a, b) => a.order - b.order || a.name.localeCompare(b.name, 'ko'));

function DialogBox({ dialog, folders, projects, counts, scope, actions, close }: { dialog: Exclude<Dialog, null>; folders: Folder[]; projects: Project[]; counts: ReadonlyMap<string, number>; scope: Scope; actions: OrganizationActions; close(): void }) {
  const initial = dialog.type === 'rename-folder' ? folders.find((x) => x.id === dialog.id)?.name ?? '' : dialog.type === 'rename-project' ? projects.find((x) => x.id === dialog.id)?.name ?? '' : '';
  const [value, setValue] = useState(initial); const input = useRef<HTMLInputElement>(null); const cancel = useRef<HTMLButtonElement>(null); const returnFocus = useRef<HTMLElement | null>(document.activeElement instanceof HTMLElement ? document.activeElement : null); const deleting = dialog.type.startsWith('delete');
  useEffect(() => { cancel.current?.focus(); return () => { requestAnimationFrame(() => returnFocus.current?.isConnected && returnFocus.current.focus()); }; }, []);
  const submit = () => { if (dialog.type === 'folder') actions.createFolder(value.trim()); else if (dialog.type === 'project') actions.createProject(value.trim(), scope?.type === 'folder' ? scope.id : null); else if (dialog.type === 'rename-folder' && dialog.id) actions.renameFolder(dialog.id, value.trim()); else if (dialog.type === 'rename-project' && dialog.id) actions.renameProject(dialog.id, value.trim()); else if (dialog.type === 'delete-folder' && dialog.id) actions.deleteFolder(dialog.id); else if (dialog.type === 'delete-project' && dialog.id) actions.deleteProject(dialog.id); close(); };
  const title = dialog.type === 'folder' ? '폴더 만들기' : dialog.type === 'project' ? '프로젝트 만들기' : dialog.type === 'rename-folder' ? '폴더 이름 변경' : dialog.type === 'rename-project' ? '프로젝트 이름 변경' : dialog.type === 'delete-folder' ? '폴더 삭제' : '프로젝트 삭제';
  return <div className="org-dialog-backdrop" onMouseDown={close} role="presentation"><form className="org-dialog" role="dialog" aria-modal="true" aria-labelledby="org-dialog-title" onMouseDown={(e) => e.stopPropagation()} onKeyDown={(e) => { if (e.key === 'Escape') { e.preventDefault(); close(); } if (e.key === 'Tab') { const buttons = [...e.currentTarget.querySelectorAll<HTMLElement>('button,input,select')].filter((node) => !node.hasAttribute('disabled')); const first = buttons[0]; const last = buttons.at(-1); if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last?.focus(); } else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first?.focus(); } } }} onSubmit={(e) => { e.preventDefault(); if (deleting || value.trim()) submit(); }}><h2 id="org-dialog-title">{title}</h2>{deleting ? <p>{dialog.type === 'delete-folder' ? '폴더 안의 프로젝트는 미분류 프로젝트로 이동합니다.' : `자료 ${counts.get(dialog.id ?? '') ?? 0}개의 프로젝트 소속만 해제됩니다. 원본 자료는 남습니다.`}</p> : <label>이름<input ref={input} maxLength={100} value={value} onChange={(e) => setValue(e.target.value)} /></label>}<div><button ref={cancel} type="button" onClick={close}>취소</button><button type="submit" className={deleting ? 'danger' : ''}>{deleting ? '삭제' : '확인'}</button></div></form></div>;
}

function TreeRow({ folder, project, count, expanded, active, drag, dropTarget, actions, peers, folders, onScope, onToggle, onDialog, onMenu, menu, onDragStart, onDragOver, onDrop }: { folder?: Folder; project?: Project; count?: number; expanded?: boolean; active: boolean; drag: string | null; dropTarget: string | null; actions: OrganizationActions; peers: Project[]; folders: Folder[]; onScope(scope: Scope): void; onToggle?(): void; onDialog(dialog: Exclude<Dialog, null>): void; onMenu(id: string | null): void; menu: string | null; onDragStart(e: DragEvent, token: string): void; onDragOver(e: DragEvent, token: string): void; onDrop(e: DragEvent, token: string): void }) {
  const entity = folder ?? project!; const token = `${folder ? 'folder' : 'project'}:${entity.id}`; const index = peers.findIndex((x) => x.id === entity.id);
  const move = (beforeId?: string) => { if (project) actions.moveProject(project.id, project.folderId, beforeId); onMenu(null); };
  const folderIndex = folders.findIndex((value) => value.id === entity.id);
  const moveFolder = (beforeId?: string) => { actions.moveFolder(entity.id, beforeId); onMenu(null); };
  return <div className={`org-tree-row ${project ? 'project' : 'folder'} ${active ? 'active' : ''} ${drag === token ? 'dragging' : ''} ${dropTarget === token ? 'drop-target' : ''}`} onDragOver={(e) => onDragOver(e, token)} onDrop={(e) => onDrop(e, token)}><button draggable className="drag-handle" onDragStart={(e) => onDragStart(e, token)} aria-label={`${entity.name} 이동 또는 순서 변경`} title="끌어서 이동">⠿</button><button className="org-tree-name" onClick={() => folder ? onToggle?.() : onScope({ type: 'project', id: entity.id })}>{folder ? `${expanded ? '⌄' : '›'} ${entity.name}` : <>▹ {entity.name}<small>{count ?? 0}</small></>}</button><button className="org-row-action" aria-haspopup="menu" aria-expanded={menu === token} onClick={() => onMenu(menu === token ? null : token)}>···</button>{dropTarget === token && <span className="org-drop-hint" role="status">{folder ? `${entity.name} 폴더로 이동` : `${entity.name} 프로젝트에 놓기`}</span>}{menu === token && <div className="org-menu" role="menu">{folder ? <><button role="menuitem" onClick={() => { onDialog({ type: 'rename-folder', id: entity.id }); onMenu(null); }}>이름 변경</button><button role="menuitem" onClick={() => moveFolder(folders[0]?.id === entity.id ? undefined : folders[0]?.id)}>맨 위로</button><button role="menuitem" disabled={folderIndex <= 0} onClick={() => moveFolder(folders[folderIndex - 1]?.id)}>위로</button><button role="menuitem" disabled={folderIndex < 0 || folderIndex === folders.length - 1} onClick={() => moveFolder(folders[folderIndex + 2]?.id)}>아래로</button><button role="menuitem" onClick={() => moveFolder()}>맨 아래로</button><button role="menuitem" className="danger-text" onClick={() => { onDialog({ type: 'delete-folder', id: entity.id }); onMenu(null); }}>폴더 삭제</button></> : <><button role="menuitem" onClick={() => { onDialog({ type: 'rename-project', id: entity.id }); onMenu(null); }}>이름 변경</button><button role="menuitem" onClick={() => move(peers[0]?.id === entity.id ? undefined : peers[0]?.id)}>맨 위로</button><button role="menuitem" disabled={index <= 0} onClick={() => move(peers[index - 1]?.id)}>위로</button><button role="menuitem" disabled={index < 0 || index === peers.length - 1} onClick={() => move(peers[index + 2]?.id)}>아래로</button><button role="menuitem" onClick={() => move()}>맨 아래로</button><label className="org-menu-label">폴더로 이동<select aria-label={`${entity.name} 폴더로 이동`} value={project!.folderId ?? ''} onChange={(e) => { actions.moveProject(project!.id, e.target.value || null); onMenu(null); }}><option value="">미분류 프로젝트</option>{folders.map((f) => <option key={f.id} value={f.id}>{f.name}</option>)}</select></label><button role="menuitem" className="danger-text" onClick={() => { onDialog({ type: 'delete-project', id: entity.id }); onMenu(null); }}>프로젝트 삭제</button></>}</div>}</div>;
}

export function FolderProjectList({ folder, projects, counts, onScope }: { folder: Folder; projects: Project[]; counts: ReadonlyMap<string, number>; onScope(scope: Scope): void }) { const entries = sort(projects.filter((p) => p.folderId === folder.id)); return <section className="org-folder-project-list" aria-label={`${folder.name} 프로젝트`}><div className="org-breadcrumb">내 정리 <span>›</span> {folder.name}</div><div className="org-card-grid">{entries.map((project) => <button className="org-project-card" key={project.id} onClick={() => onScope({ type: 'project', id: project.id })}><span>프로젝트</span><strong>{project.name}</strong><small>{counts.get(project.id) ?? 0}개 자료</small></button>)}{entries.length === 0 && <p className="muted">이 폴더에는 아직 프로젝트가 없습니다.</p>}</div></section>; }

export default function OrganizationPanel({ folders, projects, counts, scope, onScope, actions, open, onOpen, onClose }: { folders: Folder[]; projects: Project[]; counts: ReadonlyMap<string, number>; scope: Scope; onScope(scope: Scope): void; actions: OrganizationActions; open: boolean; onOpen(): void; onClose(): void }) {
  const sortedFolders = useMemo(() => sort(folders), [folders]); const sortedProjects = useMemo(() => sort(projects), [projects]); const [expanded, setExpanded] = useState<Set<string>>(() => new Set()); const [dialog, setDialog] = useState<Dialog>(null); const [menu, setMenu] = useState<string | null>(null); const [drag, setDrag] = useState<string | null>(null); const [dropTarget, setDropTarget] = useState<string | null>(null); const cancelled = useRef(false); const expandTimer = useRef<number | null>(null);
  const projectFor = (folderId: string | null) => sortedProjects.filter((p) => p.folderId === folderId); const finish = () => { setDrag(null); setDropTarget(null); if (expandTimer.current) window.clearTimeout(expandTimer.current); expandTimer.current = null; };
  useEffect(() => { const cancel = (e: KeyboardEvent) => { if (e.key === 'Escape') { cancelled.current = true; finish(); setMenu(null); } }; addEventListener('keydown', cancel); return () => removeEventListener('keydown', cancel); }, []);
  const dragStart = (e: DragEvent, token: string) => { cancelled.current = false; e.dataTransfer.effectAllowed = 'move'; e.dataTransfer.setData('text/kms-org', token); setDrag(token); };
  const dragOver = (e: DragEvent, token: string) => { if (e.dataTransfer.types.includes('text/kms-org') || e.dataTransfer.types.includes('text/kms-item-id')) { e.preventDefault(); e.dataTransfer.dropEffect = 'move'; setDropTarget(token); if (token.startsWith('folder:') && !expanded.has(token.slice(7)) && expandTimer.current === null) expandTimer.current = window.setTimeout(() => { setExpanded((old) => new Set(old).add(token.slice(7))); expandTimer.current = null; }, 550); const edge = 48; if (e.clientY < edge) window.scrollBy({ top: -18, behavior: 'auto' }); if (e.clientY > window.innerHeight - edge) window.scrollBy({ top: 18, behavior: 'auto' }); } };
  const drop = (e: DragEvent, target: string) => { e.preventDefault(); if (cancelled.current) { cancelled.current = false; finish(); return; } const source = e.dataTransfer.getData('text/kms-org'); const itemId = e.dataTransfer.getData('text/kms-item-id'); if (itemId && target.startsWith('project:')) actions.moveItemToProject?.(itemId, target.slice(8)); else if (source && source !== target) { const cut = source.indexOf(':'); const targetCut = target.indexOf(':'); const type = source.slice(0, cut); const id = source.slice(cut + 1); const targetType = target.slice(0, targetCut); const targetId = target.slice(targetCut + 1); if (type === 'folder' && targetType === 'folder') actions.moveFolder(id, targetId); if (type === 'project' && targetType === 'folder') actions.moveProject(id, targetId); if (type === 'project' && targetType === 'project') actions.moveProject(id, projects.find((x) => x.id === targetId)?.folderId ?? null, targetId); } finish(); };
  const rowProps = (active: boolean, peers: Project[]) => ({ active, drag, dropTarget, actions, peers, folders: sortedFolders, onScope, onDialog: setDialog, onMenu: setMenu, menu, onDragStart: dragStart, onDragOver: dragOver, onDrop: drop });
  return <><button className="org-drawer-toggle" aria-expanded={open} onClick={() => open ? onClose() : onOpen()}>내 정리</button><section className={`organization-panel ${open ? 'open' : ''}`} aria-label="내 정리"><div className="org-panel-head"><p className="nav-label">내 정리</p><div><button onClick={() => setDialog({ type: 'folder' })} aria-label="폴더 만들기">＋</button><button className="org-close" onClick={onClose} aria-label="내 정리 닫기">×</button></div></div><p className="org-storage-note">이 브라우저에 저장됨</p><div className="org-tree" onDragEnd={finish}>{sortedFolders.map((folder) => { const isExpanded = expanded.has(folder.id); return <div className="org-folder" key={folder.id}><TreeRow folder={folder} expanded={isExpanded} {...rowProps(scope?.type === 'folder' && scope.id === folder.id, [])} onToggle={() => setExpanded((old) => { const next = new Set(old); next.has(folder.id) ? next.delete(folder.id) : next.add(folder.id); return next; })} />{isExpanded && <div className="org-projects">{projectFor(folder.id).map((project) => <TreeRow key={project.id} project={project} count={counts.get(project.id)} {...rowProps(scope?.type === 'project' && scope.id === project.id, projectFor(folder.id))} />)}</div>}</div>; })}<div className={`org-unfiled ${dropTarget === 'unfiled' ? 'drop-target' : ''}`} onDragOver={(e) => dragOver(e, 'unfiled')} onDrop={(e) => { if (drag?.startsWith('project:')) { e.preventDefault(); actions.moveProject(drag.slice(8), null); finish(); } }}><p>미분류 프로젝트</p>{projectFor(null).map((project) => <TreeRow key={project.id} project={project} count={counts.get(project.id)} {...rowProps(scope?.type === 'project' && scope.id === project.id, projectFor(null))} />)}{projectFor(null).length === 0 && <p className="org-drop-empty">프로젝트를 여기에 놓기</p>}</div></div><div className="org-panel-footer"><button onClick={() => setDialog({ type: 'project' })}>프로젝트 만들기</button><button onClick={actions.exportJson}>내보내기</button><label>가져오기<input type="file" accept="application/json" onChange={(e) => { const file = e.currentTarget.files?.[0]; if (file) actions.importJson(file); e.currentTarget.value = ''; }} /></label></div></section>{dialog && <DialogBox dialog={dialog} folders={folders} projects={projects} counts={counts} scope={scope} actions={actions} close={() => setDialog(null)} />}</>;
}
